### PR TITLE
Update to PureScript v0.15.0

### PR DESCRIPTION
**Pull request by JordanMartinez**
**Description of the change**

Backlinking to purescript/purescript#4244

Migrates FFI to ES modules

---

**Checklist:**

- [x] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by JordanMartinez** [comment]
:ping_pong: @thomashoneyman CI will fail due to using `spago` to bundle things. Since this isn't exactly a commonly-used lib, how do you want to proceed?

**Comment by thomashoneyman** [comment]
My initial thought is to use `esbuild` directly to bundle, as will be done under the hood with Spago in the future. Does that seem like an appropriate plan? Perhaps @sigma-andex knows the correct way to do this?

Otherwise, we could comment out the tests, create an issue to come back to it, and move on.

Either way we need to add `aff-promise` to the `prepare-0.15` package set.

**Comment by JordanMartinez** [comment]
> Either way we need to add aff-promise to the prepare-0.15 package set.

Ah, good point.

**Comment by JordanMartinez** [comment]
> My initial thought is to use esbuild directly to bundle, as will be done under the hood with Spago in the future. Does that seem like an appropriate plan? Perhaps @sigma-andex knows the correct way to do this?

That can work. Maybe do that for now and then use `spago bundle`, which will use `esbuild` under the hood, later?

**Comment by sigma-andex** [comment]
This is running on node, right? If so we don't even need to bundle

**Comment by sigma-andex** [comment]
If you want to bundle, this can be used:
```
[debug] Running command: `echo "import { main } from './output/Main/index.js'
main()" | /usr/local/bin/esbuild --platform=node --format=esm --bundle  --outfile=index.js`
```

**Comment by JordanMartinez** [comment]
> This is running on node, right? If so we don't even need to bundle

Thanks for the tip!

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
