### PR TITLE
Update to v0.14.0-rc3

### PR DESCRIPTION
**Pull request by JordanMartinez**
Backlinking to purescript-contrib/governance#35

### CODE REVIEW

**Comment by JordanMartinez** [comment]
I'm just getting this PR started, so it's easier to do node and web libraries.

**Comment by colinwahl** [comment]
Thank you @JordanMartinez !

**Review by thomashoneyman — APPROVED** [review]

**Comment by JordanMartinez** [comment]
Just FYI. This repo depends on a non-contrib repo: [`aff-promise`](https://github.com/nwolverson/purescript-aff-promise). Is that an issue?

**Comment by thomashoneyman** [comment]
Hm -- in an ideal world we wouldn't rely on a non-core or non-contrib repository, though we sometimes make small exceptions. We should probably make an issue to inline the relevant code from `aff-promise` here so that we can make necessary changes for 0.14 and not bring in incorrect Bower dependencies. Perhaps @colinwahl would be OK making that change to drop the dependency?

**Pull request merged**
